import type { Metadata } from "next";
import type { EventItem } from "@/lib/events";

export const SITE_NAME = "Scout FX";

// Generated by src/app/opengraph-image.tsx; pages with their own opengraph-image.tsx pass theirs.
const DEFAULT_IMAGE = "/opengraph-image";

/**
 * Title, description and link-preview (Open Graph / X) tags for one page.
 * `path` is the clean page URL (no UTM tags), used as the canonical and og:url.
 * `image` is the page's generated preview (its opengraph-image.tsx route); without
 * it the site-wide image is used. Setting images here overrides file-based ones,
 * which is why it has to be passed explicitly.
 */
export function buildMetadata({
  title,
  description,
  path,
  shareTitle = typeof title === "string" ? title : title.absolute,
  image = DEFAULT_IMAGE,
  imageAlt = shareTitle,
}: {
  /** Tab title; " | Scout FX" is added by the layout unless given as { absolute }. */
  title: string | { absolute: string };
  description: string;
  path: string;
  /** Title shown in social previews, if it should differ from the browser tab title. */
  shareTitle?: string;
  image?: string;
  imageAlt?: string;
}): Metadata {
  const images = [{ url: image, width: 1200, height: 630, alt: imageAlt, type: "image/png" }];
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      title: shareTitle,
      description,
      url: path,
      siteName: SITE_NAME,
      type: "website",
      locale: "en_GB",
      images,
    },
    twitter: { card: "summary_large_image", title: shareTitle, description, images },
  };
}

/** "Saturday, October 31, 2026 · 11:00 AM GMT" -> "Sat 31 Oct". */
export function shortEventDate(event: EventItem) {
  if (!event.dateISO) return event.date.split(" · ")[0];
  const d = new Date(event.dateISO);
  const part = (o: Intl.DateTimeFormatOptions) => d.toLocaleDateString("en-GB", { ...o, timeZone: "UTC" });
  return `${part({ weekday: "short" })} ${part({ day: "numeric" })} ${part({ month: "short" })}`;
}

/** "11:00 AM GMT" from the event's display date. */
export function eventTime(event: EventItem) {
  return event.date.split(" · ")[1] ?? "";
}

/** The town at the end of "Miklin Hotel, Accra". */
export function eventCity(event: EventItem) {
  return event.location.split(",").pop()!.trim();
}
