import Link from "next/link";
import { Container, Eyebrow, StatCard, PrimaryButton, SecondaryButton } from "@/components/ui";
import { Activity, Target, TrendingUp, AlertTriangle, ListChecks, Bell, ShieldCheck } from "lucide-react";

const stats = [
  { label: "Logged signals", value: "312" },
  { label: "Win rate", value: "58%" },
  { label: "Avg. R:R", value: "1:1.8" },
];

const steps = [
  { icon: Activity, title: "A rule triggers", desc: "Price and an indicator (RSI, MACD, moving averages) hit a defined condition on a tracked pair." },
  { icon: ListChecks, title: "The signal is logged", desc: "Pair, direction, entry, stop and target are recorded immediately and permanently, before the outcome is known." },
  { icon: Bell, title: "You get notified", desc: "In-app, Telegram or email, your choice, set after you accept the risk disclosure." },
];

export default function SignalsLandingPage() {
  return (
    <section className="py-16">
      <Container>
        <Eyebrow>Rule-based, logged, public</Eyebrow>
        <h1 className="mt-5 max-w-xl text-4xl font-bold leading-[1.05] tracking-tight text-gradient animate-fade-up pb-1 sm:text-5xl">
          Signals with a track record you can check
        </h1>
        <p className="mt-4 max-w-lg text-base leading-relaxed text-zinc-400">
          Every signal is generated from a fixed rule, logged the moment it
          fires, and never edited after the fact. The full history,
          including losses, is public.
        </p>

        <div className="mt-6 flex flex-col gap-3 sm:flex-row">
          <PrimaryButton href="/signals/dashboard">Get access</PrimaryButton>
          <SecondaryButton href="/signals/history">See full track record</SecondaryButton>
        </div>

        <div className="mt-10 flex items-start gap-3 rounded-2xl border border-danger/20 bg-danger/5 p-4">
          <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-danger" />
          <p className="text-xs leading-relaxed text-zinc-300">
            Signals are generated by a rule-based system, not guaranteed
            predictions. Trading carries a high risk of loss. Read the{" "}
            <Link href="/signals/disclosure" className="underline">
              full risk disclosure
            </Link>{" "}
            before requesting access.
          </p>
        </div>

        {/* live stats */}
        <div className="mt-14">
          <h2 className="text-sm font-bold uppercase tracking-wide text-zinc-400">
            Track record: all-time
          </h2>
          <div className="mt-5 grid grid-cols-3 gap-4">
            <StatCard icon={<ListChecks className="h-4 w-4 text-brand-500" />} iconBg="bg-brand-500/10" label={stats[0].label} value={stats[0].value} />
            <StatCard icon={<Target className="h-4 w-4 text-black" />} iconBg="bg-brand-600" label={stats[1].label} value={stats[1].value} />
            <StatCard icon={<TrendingUp className="h-4 w-4 text-brand-500" />} iconBg="bg-brand-500/10" label={stats[2].label} value={stats[2].value} />
          </div>
        </div>

        {/* how it works */}
        <div className="mt-16">
          <h2 className="text-sm font-bold uppercase tracking-wide text-zinc-400">
            How it works
          </h2>
          <div className="mt-5 grid gap-5 sm:grid-cols-3">
            {steps.map((s) => (
              <div key={s.title} className="card p-5">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-brand-500/10">
                  <s.icon className="h-5 w-5 text-white" />
                </div>
                <h3 className="mt-3 text-sm font-bold text-white">{s.title}</h3>
                <p className="mt-1 text-xs leading-relaxed text-zinc-400">{s.desc}</p>
              </div>
            ))}
          </div>
        </div>

        <div className="mt-16 flex items-center gap-4 rounded-3xl border border-white/10 bg-white/[0.02] p-6">
          <ShieldCheck className="h-6 w-6 shrink-0 text-brand-500" />
          <p className="text-sm text-zinc-300">
            All client and trading activity applies to verified adults and
            remains subject to HFM compliance and reporting rules.
          </p>
        </div>
      </Container>
    </section>
  );
}
