"use client";

import { useState, FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Container } from "@/components/ui";
import { AlertTriangle, Loader2 } from "lucide-react";

export default function SignalsDisclosurePage() {
  const router = useRouter();
  const [email, setEmail] = useState("");
  const [checked, setChecked] = useState(false);
  const [status, setStatus] = useState<"idle" | "loading" | "error">("idle");
  const [errorMsg, setErrorMsg] = useState("");

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    if (!checked) return;
    setStatus("loading");
    setErrorMsg("");

    try {
      const res = await fetch("/api/signals/accept-disclosure", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data?.error || "Something went wrong");

      // MVP client-side gate flag. Swap for a real session/Firebase Auth
      // check once auth is wired up.
      localStorage.setItem("signals_disclosure_accepted", "true");
      localStorage.setItem("signals_user_email", email.trim().toLowerCase());
      router.push("/signals/dashboard");
    } catch (err) {
      setStatus("error");
      setErrorMsg(err instanceof Error ? err.message : "Something went wrong");
    }
  }

  return (
    <section className="py-16">
      <Container className="max-w-xl">
        <h1 className="text-3xl font-extrabold tracking-tight text-ink-900">
          Risk disclosure
        </h1>
        <p className="mt-2 text-sm text-ink-500">
          Read this in full before you get access to live signals.
        </p>

        <div className="mt-6 max-h-72 space-y-4 overflow-y-auto rounded-2xl border border-ink-100 bg-ink-100/20 p-5 text-sm leading-relaxed text-ink-700">
          <p>
            Trading foreign exchange, gold, cryptocurrency and other leveraged
            products carries a high level of risk and may not be suitable
            for all investors. You could lose some or all of your invested
            capital; you should not invest money that you cannot afford to
            lose.
          </p>
          <p>
            Signals published on this site are generated by a rule-based
            system built on technical indicators applied to historical and
            live price data. They reflect a defined set of conditions being
            met. They are not predictions, personalized investment advice,
            or a guarantee of any outcome, and past performance shown on
            this site is not indicative of future results.
          </p>
          <p>
            Every signal is logged automatically and permanently at the
            moment it fires, and the record, including losing signals, is
            not edited, hidden or removed after the fact.
          </p>
          <p>
            You are solely responsible for your own trading decisions. This
            service does not manage funds, execute trades on your behalf, or
            provide fiduciary advice. Nothing on this site should be
            construed as an offer or solicitation to buy or sell any
            financial instrument.
          </p>
          <p>
            By accepting, you confirm you are of legal trading age in your
            jurisdiction and understand the risks described above.
          </p>
        </div>

        <form onSubmit={handleSubmit} className="mt-6 space-y-4">
          <input
            type="email"
            required
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            placeholder="you@email.com"
            className="w-full rounded-xl border border-ink-100 px-4 py-2.5 text-sm text-ink-900 placeholder:text-ink-300 focus:border-brand-400"
          />

          <label className="flex items-start gap-3 text-sm text-ink-700">
            <input
              type="checkbox"
              checked={checked}
              onChange={(e) => setChecked(e.target.checked)}
              className="mt-0.5 h-4 w-4 rounded border-ink-100 text-brand-800 focus:ring-brand-400"
            />
            I have read and understood the risk disclosure above, and I
            accept it.
          </label>

          <button
            type="submit"
            disabled={!checked || status === "loading"}
            className="flex w-full items-center justify-center gap-2 rounded-full bg-brand-600 px-6 py-3 text-sm font-semibold text-ink-900 transition-colors hover:bg-brand-700 disabled:opacity-50"
          >
            {status === "loading" && <Loader2 className="h-4 w-4 animate-spin" />}
            Accept &amp; continue to signals
          </button>

          {status === "error" && (
            <p className="flex items-center gap-2 text-sm text-danger">
              <AlertTriangle className="h-4 w-4" /> {errorMsg}
            </p>
          )}
        </form>
      </Container>
    </section>
  );
}
