import { Container } from "@/components/ui";

export default function RiskDisclosurePage() {
  return (
    <section className="py-16">
      <Container className="max-w-2xl">
        <h1 className="text-3xl font-bold leading-[1.05] tracking-tight text-gradient animate-fade-up pb-1">
          Risk Disclosure
        </h1>
        <p className="mt-2 text-sm text-zinc-500">Last updated: August 2026</p>

        <div className="mt-8 space-y-6 text-sm leading-relaxed text-zinc-300">
          <p>
            Trading foreign exchange (forex), gold, cryptocurrency and other
            leveraged or CFD products carries a high level of risk and may
            not be suitable for all investors. Before deciding to trade, you
            should carefully consider your investment objectives, level of
            experience and risk appetite.
          </p>
          <p>
            <strong className="text-white">No guarantees.</strong> Nothing
            published on this site, including educational content and
            signals, is a guarantee of profit or a promise of any
            particular outcome. Past performance, including any track
            record shown, is not indicative of future results.
          </p>
          <p>
            <strong className="text-white">Educational content.</strong>{" "}
            Articles in the education library explain how markets and
            indicators work. They are general information, not personalized
            investment advice, and should not be relied on as the sole basis
            for any trading decision.
          </p>
          <p>
            <strong className="text-white">Signals.</strong> Signals are
            generated by a rule-based system applying defined technical
            conditions to price data. They reflect that a condition was met,
            not a prediction of future price movement. Every signal is
            logged automatically at the time it is generated and is not
            edited or removed after the fact, including losing signals.
          </p>
          <p>
            <strong className="text-white">Your responsibility.</strong>{" "}
            You are solely responsible for your own trading and investment
            decisions. This service does not manage funds on your behalf,
            execute trades for you, or act as a fiduciary or licensed
            investment adviser.
          </p>
          <p>
            <strong className="text-white">Broker relationship.</strong>{" "}
            Scout FX is an HFM affiliate (Affiliate ID: 30537791) and
            may receive compensation based on referrals, registrations and
            trading activity generated through this site. This is a
            potential conflict of interest you should be aware of when
            evaluating any content, seminar or signal referencing HFM.
          </p>
          <p>
            <strong className="text-white">Age &amp; jurisdiction.</strong>{" "}
            Access to signals and trading-related content is intended for
            adults of legal trading age in their jurisdiction. It is your
            responsibility to ensure that trading is legal in your
            jurisdiction before proceeding.
          </p>
          <p>
            Questions about this disclosure can be sent to
            hello@scoutsfx.com.
          </p>
        </div>
      </Container>
    </section>
  );
}
