import { Container } from "@/components/ui";
import Link from "next/link";
import { buildMetadata } from "@/lib/seo";

export const metadata = buildMetadata({
  title: "Compliance & affiliate disclosure",
  description: "How Scout FX handles affiliate relationships, signals and education responsibly.",
  path: "/compliance",
});

export default function CompliancePage() {
  return (
    <section className="py-16">
      <Container className="max-w-2xl">
        <h1 className="text-3xl font-bold leading-[1.05] tracking-tight text-gradient animate-fade-up pb-1">
          Compliance
        </h1>
        <p className="mt-2 text-sm text-zinc-500">Last updated: August 2026</p>

        <div className="mt-8 space-y-6 text-sm leading-relaxed text-zinc-300">
          <p>
            Scout FX operates as a trading education and community
            platform, not as a licensed broker, fund manager or investment
            adviser. This page summarizes how we handle affiliate
            relationships, disclosures and data. See the full{" "}
            <Link href="/legal/risk-disclosure" className="underline">
              risk disclosure
            </Link>{" "}
            for trading-specific risk information.
          </p>
          <p>
            <strong className="text-white">Affiliate disclosure.</strong>{" "}
            Scout FX is an HFM affiliate (Affiliate ID: 30537791) and may
            earn compensation when someone registers or trades through a
            link on this site. This is disclosed wherever HFM is referenced,
            including in seminars and signal content.
          </p>
          <p>
            <strong className="text-white">Signal integrity.</strong>{" "}
            Signals are generated by a rule-based system and logged
            automatically at the time they are produced. Records are not
            edited or removed after the fact, including losing signals. See
            the published{" "}
            <Link href="/signals/history" className="underline">
              track record
            </Link>
            .
          </p>
          <p>
            <strong className="text-white">Data handling.</strong> Contact
            details submitted through sign-up and RSVP forms are used to send
            the requested content or event information and are not sold to
            third parties.
          </p>
          <p>
            <strong className="text-white">No advisory relationship.</strong>{" "}
            Joining the community, attending an event, or receiving a signal
            does not create a fiduciary, advisory or client relationship. See
            the full{" "}
            <Link href="/legal/terms" className="underline">
              terms of service
            </Link>
            .
          </p>
          <p>
            Compliance questions can be sent to hello@scoutsfx.com.
          </p>
        </div>
      </Container>
    </section>
  );
}
